export type EstadoDeCuenta = {
  pagoEnero: boolean,
  pagoFebrero: boolean,
  pagoMarzo: boolean,
  pagoAbril: boolean,
  pagoMayo: boolean,
  pagoJunio: boolean,
  pagoJulio: boolean,
  pagoAgosto: boolean,
  pagoSeptiembre: boolean,
  pagoOctubre: boolean,
  pagoNoviembre: boolean,
  pagoDiciembre: boolean,
};

export type EstadoDeCuentaFormType = {
  idRecorrido: number,
  idPasajero: number,
  pagoEnero: boolean,
  pagoFebrero: boolean,
  pagoMarzo: boolean,
  pagoAbril: boolean,
  pagoMayo: boolean,
  pagoJunio: boolean,
  pagoJulio: boolean,
  pagoAgosto: boolean,
  pagoSeptiembre: boolean,
  pagoOctubre: boolean,
  pagoNoviembre: boolean,
  pagoDiciembre: boolean,
};

export const EstadoDeCuentaTexto = {
  pagoEnero: 'Enero',
  pagoFebrero: 'Febrero',
  pagoMarzo: 'Marzo',
  pagoAbril: 'Abril',
  pagoMayo: 'Mayo',
  pagoJunio: 'Junio',
  pagoJulio: 'Julio',
  pagoAgosto: 'Agosto',
  pagoSeptiembre: 'Septiembre',
  pagoOctubre: 'Octubre',
  pagoNoviembre: 'Noviembre',
  pagoDiciembre: 'Diciembre',
};
